alias la='ls -lAh'
alias ll='ls -lh'
alias ls='ls --color=tty'

export test='{{myVarTest}}'


# TODO Ansible ansible :p
source ~/gitRepo/ansible/hacking/env-setup

# Source all files in chunks folder
BASH_CHUNKS_FOLDER={{folder.chunks}}
if [ -d $BASH_CHUNKS_FOLDER ]; then
  for bashrc_chunk in $BASH_CHUNKS_FOLDER/*
  do
    source $bashrc_chunk
  done
fi
