- name: Install Atom packages
  apt: name=atom state=latest

- name: Install Atom Plugins
  shell: apm install {{ item }}
  with_items:
    - eclipse-keybindings
    - langage-asciidoc
    - asciidoc-preview
    - language-groovy
    - atom-beautify
    - atom-typescript
    - pigments
    - color-picker
    - sass-autocompile
